[package]
name = "rpac"
version = "0.1.0"
edition = "2021"

[dependencies]
boa_engine ="0.19"
reqwest = "0.11"
url = "2"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }